# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-26 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('min_length', models.PositiveIntegerField()),
                ('max_length', models.PositiveIntegerField()),
                ('regex', models.CharField(blank=True, default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('form', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
                ('phase', models.CharField(default='ALPHA', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Form')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('website', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('pattern', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, default='')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='sections',
            field=models.ManyToManyField(through='forms.SectionQuestion', to='forms.Question'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Section'),
        ),
        migrations.AddField(
            model_name='form',
            name='organisations',
            field=models.ManyToManyField(to='forms.Organisation'),
        ),
        migrations.AddField(
            model_name='form',
            name='sections',
            field=models.ManyToManyField(through='forms.FormSection', to='forms.Section'),
        ),
        migrations.AddField(
            model_name='field',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Pattern'),
        ),
    ]
