# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('datatype', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('inputtype', models.CharField(blank=True, default='', max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=256)),
                ('value', models.CharField(blank=True, default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.DataType')),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.List')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Item')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='field',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='field',
            name='max_length',
        ),
        migrations.RemoveField(
            model_name='field',
            name='min_length',
        ),
        migrations.RemoveField(
            model_name='field',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='field',
            name='regex',
        ),
        migrations.RemoveField(
            model_name='form',
            name='name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='field',
        ),
        migrations.RemoveField(
            model_name='section',
            name='name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='sections',
        ),
        migrations.AddField(
            model_name='field',
            name='hint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='form',
            name='heading',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='form',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='guidance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='heading',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='warning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='guidance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='heading',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='section',
            name='questions',
            field=models.ManyToManyField(through='forms.SectionQuestion', to='forms.Question'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='phase',
            field=models.ForeignKey(default='alpha', on_delete=django.db.models.deletion.CASCADE, to='forms.Phase'),
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
        migrations.AddField(
            model_name='questionfield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Field'),
        ),
        migrations.AddField(
            model_name='questionfield',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Question'),
        ),
        migrations.AddField(
            model_name='list',
            name='items',
            field=models.ManyToManyField(through='forms.ListItem', to='forms.Item'),
        ),
        migrations.AddField(
            model_name='field',
            name='blacklists',
            field=models.ManyToManyField(related_name='blacklists', to='forms.List'),
        ),
        migrations.AddField(
            model_name='field',
            name='datatype',
            field=models.ForeignKey(default='string', on_delete=django.db.models.deletion.CASCADE, to='forms.DataType'),
        ),
        migrations.AddField(
            model_name='field',
            name='inputtype',
            field=models.ForeignKey(default='text', on_delete=django.db.models.deletion.CASCADE, to='forms.InputType'),
        ),
        migrations.AddField(
            model_name='field',
            name='whitelists',
            field=models.ManyToManyField(related_name='whitelists', to='forms.List'),
        ),
        migrations.AddField(
            model_name='question',
            name='fields',
            field=models.ManyToManyField(through='forms.QuestionField', to='forms.Field'),
        ),
    ]
