# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.TextField(blank=True, default='')),
                ('guidance', models.TextField(blank=True, default='')),
                ('warning', models.TextField(blank=True, default='')),
                ('detail', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RenameModel(
            old_name='QuestionField',
            new_name='PageField',
        ),
        migrations.RenameModel(
            old_name='SectionQuestion',
            new_name='SectionPage',
        ),
        migrations.RemoveField(
            model_name='question',
            name='fields',
        ),
        migrations.RemoveField(
            model_name='pagefield',
            name='question',
        ),
        migrations.RemoveField(
            model_name='section',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='sectionpage',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='page',
            name='fields',
            field=models.ManyToManyField(through='forms.PageField', to='forms.Field'),
        ),
        migrations.AddField(
            model_name='pagefield',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forms.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='pages',
            field=models.ManyToManyField(through='forms.SectionPage', to='forms.Page'),
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='forms.Page'),
            preserve_default=False,
        ),
    ]
