# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20171123_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsection',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='questionfield',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='sectionquestion',
            options={'ordering': ['number']},
        ),
        migrations.RenameField(
            model_name='formsection',
            old_name='order',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='listitem',
            old_name='order',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='questionfield',
            old_name='order',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='sectionquestion',
            old_name='order',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='field',
            name='blacklists',
            field=models.ManyToManyField(blank=True, related_name='blacklists', to='forms.List'),
        ),
        migrations.AlterField(
            model_name='field',
            name='whitelists',
            field=models.ManyToManyField(blank=True, related_name='whitelists', to='forms.List'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
