# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-20 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20171120_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtype',
            name='datatype',
        ),
        migrations.RemoveField(
            model_name='fieldtype',
            name='inputtype',
        ),
        migrations.RemoveField(
            model_name='fieldtype',
            name='validation',
        ),
        migrations.RemoveField(
            model_name='field',
            name='fieldtype',
        ),
        migrations.AddField(
            model_name='field',
            name='datatype',
            field=models.ForeignKey(default='string', on_delete=django.db.models.deletion.CASCADE, to='forms.DataType'),
        ),
        migrations.AddField(
            model_name='field',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='field',
            name='inputtype',
            field=models.ForeignKey(default='text', on_delete=django.db.models.deletion.CASCADE, to='forms.InputType'),
        ),
        migrations.AddField(
            model_name='field',
            name='validation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='forms.Validation'),
        ),
        migrations.DeleteModel(
            name='FieldType',
        ),
    ]
