# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20171205_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('pagetype', models.CharField(blank=True, default='', max_length=256, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='inputtype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='page',
            name='pagetype',
            field=models.ForeignKey(default='question', on_delete=django.db.models.deletion.CASCADE, to='forms.PageType'),
        ),
    ]
